pre_cfg:
  is_recommend: 
    max_num: 4
    isrec_prompt: "LawConv/config/is_recommend.md"
    rec_prompt: "LawConv/config/recommend.md"
  extract_telephone: 
    activated: true
  sever_character:
    prompt: "LawConv/config/intent_detect.md"
    lawyer: 
      work: "LawConv/config/lawyer/work.md"
      marriage: "LawConv/config/lawyer/marriage.md"
      injury: "LawConv/config/lawyer/injury.md"
      borrow: "LawConv/config/lawyer/borrow.md"
      others: "LawConv/config/lawyer/others.md"
    psychologist: "LawConv/config/psychologist.md"
    middle: 
      work: "LawConv/config/middle/work.md"
      marriage: "LawConv/config/middle/marriage.md"
      injury: "LawConv/config/middle/injury.md"
      borrow: "LawConv/config/middle/borrow.md"
      others: "LawConv/config/middle/others.md"
    clerk: "LawConv/config/clerk.md"

post_cfg:
  max_dedup:
    max_dedup: 2
  simplify_response: 
    max_length_in_char: 50


llm:
  model: "deepseek-chat"
  api_key: ""
  api_base: "https://api.deepseek.com"
  max_tokens: 4096
  temperature: 1.0
  top_p: 1.0
  n: 1

gpt:
  model: "gpt-4o-mini"
  api_key: ""
  api_base: "https://api.openai.com/v1"
  max_tokens: 4096
  temperature: 1.0
