pre_cfg:
  mode_switch:
    key_word: "律师VIP"
  lawyer:
    prompt: "LawConv/config/lawyer.md"
    
  sever_character:
    ask: "LawConv/config/lawyer/work/ask.md"
    recommend: "LawConv/config/lawyer/work/recommend.md"
    work: 
      intent_detect: "LawConv/config/lawyer/work/intent_detect.md"
      0: "LawConv/config/lawyer/work/others.md"
      1: "LawConv/config/lawyer/work/complete.md"
      2: "LawConv/config/lawyer/work/transfer_salary.md"
      3: "LawConv/config/lawyer/work/unpaid_wages.md"
      4: "LawConv/config/lawyer/work/social_insurance.md"
      5: "LawConv/config/lawyer/work/work_injury.md"
  ask_question:
    max_turns: 4
    prompt: "LawConv/config/lawyer/ask_question.md"
  is_recommend:
    min_turns: 4
    prompt: "LawConv/config/lawyer/end_conv.md"
  emotion:
    max_turns: 2
    prompt: "LawConv/config/lawyer/emotion.md"
      
post_cfg:
  max_dedup:
    max_dedup: 2
  simplify_response: 
    max_length_in_char: 50

llm:
  model: "deepseek-chat"
  api_key: ""
  api_base: "https://api.deepseek.com"
  max_tokens: 4096
  temperature: 0.2
  top_p: 0.7
  n: 1

gpt:
  model: "gpt-4o"
  api_key: ""
  api_base: "https://api.openai.com/v1"
  max_tokens: 4096
  temperature: 0.2
  top_p: 0.7
  
